(() => {
"use strict";
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const SAVE="englishAdventureV10";
const LETTER={A:"ay",B:"bee",C:"see",D:"dee",E:"ee",F:"eff",G:"gee",H:"aitch",I:"eye",J:"jay",K:"kay",L:"ell",M:"em",N:"en",O:"oh",P:"pee",Q:"cue",R:"are",S:"ess",T:"tee"};
const WORDS=[{word:"cat",pic:"🐱"},{word:"dog",pic:"🐶"},{word:"fish",pic:"🐟"},{word:"apple",pic:"🍎"}];
let state;try{state=Object.assign({coins:0,stars:0,words:0,lastX:90},JSON.parse(localStorage.getItem(SAVE)||"{}"))}catch{state={coins:0,stars:0,words:0,lastX:90}}
let voiceName="",voiceRate=.78,activeGame=null,built=[];
function save(){localStorage.setItem(SAVE,JSON.stringify(state));hud()}
function hud(){$("#coinCount").textContent=state.coins;$("#starCount").textContent=state.stars}
function show(id){$$(".screen").forEach(x=>x.classList.remove("active"));$("#"+id).classList.add("active");if(id==="parents"){ $("#pCoins").textContent=state.coins;$("#pStars").textContent=state.stars;$("#pWords").textContent=state.words }if(id==="settings")voices()}
function shuffle(a){return [...a].sort(()=>Math.random()-.5)}
function getVoices(){return speechSynthesis.getVoices().filter(v=>/^en/i.test(v.lang)||/English/i.test(v.name))}
function voices(){const v=getVoices();$("#voiceSelect").innerHTML=v.map(x=>`<option>${x.name}</option>`).join("");if(v.length){voiceName=voiceName||v[0].name;$("#voiceSelect").value=voiceName}}
function speak(text,rate=voiceRate){speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(String(text).toLowerCase()),v=getVoices().find(x=>x.name===voiceName)||getVoices()[0];if(v)u.voice=v;u.lang=v?.lang||"en-US";u.rate=rate;speechSynthesis.speak(u)}
function spell(word){speak(word.toUpperCase().split("").map(x=>LETTER[x]).join(", "),Math.max(.62,voiceRate-.08))}
class Game{
 constructor(c){this.c=c;this.x=c.getContext("2d");this.w=3000;this.gy=455;this.cam=0;this.p={x:90,y:330,w:42,h:62,vx:0,vy:0,g:false};this.keys={l:false,r:false};this.coins=[350,530,740,980,1210,1490,1780,2100,2420,2660].map((x,i)=>({x,y:370-(i%3)*38,t:false}));this.plats=[{x:0,y:455,w:3000,h:100},{x:600,y:390,w:170,h:25},{x:1080,y:355,w:190,h:25},{x:1560,y:400,w:210,h:25},{x:2170,y:365,w:180,h:25}];this.gate={x:2800,y:335,w:88,h:120,o:false};this.run=false;this.last=0;this.bind()}
 bind(){const hold=(el,k)=>{el.onpointerdown=e=>{e.preventDefault();this.keys[k]=true};["onpointerup","onpointerleave","onpointercancel"].forEach(n=>el[n]=()=>this.keys[k]=false)};hold($("#leftBtn"),"l");hold($("#rightBtn"),"r");$("#jumpBtn").onpointerdown=e=>{e.preventDefault();if(this.p.g){this.p.vy=-660;this.p.g=false}}}
 start(cont){this.p.x=cont?Math.min(state.lastX,2700):90;this.p.y=330;this.p.vx=this.p.vy=0;this.gate.o=false;this.run=true;this.last=performance.now();requestAnimationFrame(t=>this.loop(t))}
 stop(){this.run=false;state.lastX=Math.round(this.p.x);save()}
 loop(t){if(!this.run)return;const dt=Math.min(.033,(t-this.last)/1000||.016);this.last=t;this.update(dt);this.draw();requestAnimationFrame(n=>this.loop(n))}
 update(dt){const p=this.p,old=p.y;p.vx=this.keys.l?-270:this.keys.r?270:0;p.vy+=1650*dt;p.x+=p.vx*dt;p.y+=p.vy*dt;p.x=Math.max(0,Math.min(this.w-p.w,p.x));p.g=false;for(const q of this.plats){if(old+p.h<=q.y+5&&p.y+p.h>=q.y&&p.x+p.w>q.x&&p.x<q.x+q.w&&p.vy>=0){p.y=q.y-p.h;p.vy=0;p.g=true}}if(p.y>650){p.x=90;p.y=300;p.vy=0}for(const coin of this.coins){if(!coin.t&&Math.hypot(p.x+p.w/2-coin.x,p.y+p.h/2-coin.y)<40){coin.t=true;state.coins++;save()}}if(!this.gate.o&&p.x+p.w>this.gate.x){p.x=this.gate.x-p.w-2;this.run=false;openGate(this)}this.cam+=((p.x-250)-this.cam)*Math.min(1,5*dt);this.cam=Math.max(0,Math.min(this.w-this.c.width,this.cam));state.lastX=p.x}
 draw(){const c=this.x;c.clearRect(0,0,960,540);const g=c.createLinearGradient(0,0,0,540);g.addColorStop(0,"#80d2ff");g.addColorStop(1,"#effcff");c.fillStyle=g;c.fillRect(0,0,960,540);c.save();c.translate(-this.cam,0);for(let x=100;x<this.w;x+=500){c.fillStyle="#ffffffbb";c.beginPath();c.arc(x,90,35,0,Math.PI*2);c.arc(x+40,82,42,0,Math.PI*2);c.arc(x+80,92,30,0,Math.PI*2);c.fill()}for(const q of this.plats){c.fillStyle="#70c851";c.fillRect(q.x,q.y,q.w,18);c.fillStyle="#9b633d";c.fillRect(q.x,q.y+18,q.w,q.h-18)}for(const coin of this.coins)if(!coin.t){c.fillStyle="#f5bc19";c.beginPath();c.arc(coin.x,coin.y,14,0,Math.PI*2);c.fill();c.strokeStyle="#ffe97c";c.lineWidth=5;c.stroke()}c.fillStyle=this.gate.o?"#83db97":"#7655d8";c.fillRect(this.gate.x,this.gate.y,this.gate.w,this.gate.h);c.fillStyle="#fff";c.font="bold 24px system-ui";c.textAlign="center";c.fillText(this.gate.o?"GO":"ABC",this.gate.x+44,this.gate.y+64);const p=this.p;c.fillStyle="#ffca8d";c.beginPath();c.arc(p.x+21,p.y+17,17,0,Math.PI*2);c.fill();c.fillStyle="#2e68d9";c.fillRect(p.x+7,p.y+32,28,28);c.fillStyle="#2a1d17";c.beginPath();c.arc(p.x+21,p.y+9,17,Math.PI,Math.PI*2);c.fill();c.restore()}
}
function openGate(g){activeGame=g;built=[];const it=WORDS[state.words%WORDS.length];$("#gatePicture").textContent=it.pic;$("#slots").innerHTML=it.word.split("").map(()=>'<span class="slot"></span>').join("");$("#letters").innerHTML=shuffle(it.word.toUpperCase().split("")).map(l=>`<button class="letter" data-l="${l}">${l}</button>`).join("");$("#gateMessage").textContent="";$$(".letter").forEach(b=>b.onclick=()=>press(b,it));$("#wordGate").classList.remove("hidden");setTimeout(()=>speak(it.word),200)}
function press(b,it){const e=it.word.toUpperCase()[built.length];if(b.dataset.l!==e){$("#gateMessage").textContent="ลองอีกครั้งนะ";return}b.disabled=true;built.push(e);$$(".slot")[built.length-1].textContent=e;if(built.length===it.word.length){state.stars++;state.words++;save();$("#gateMessage").textContent="เปิดประตูสำเร็จ! ⭐";activeGame.gate.o=true;setTimeout(()=>{$("#wordGate").classList.add("hidden");activeGame.p.x=activeGame.gate.x+120;activeGame.run=true;activeGame.last=performance.now();requestAnimationFrame(t=>activeGame.loop(t))},800)}}
const game=new Game($("#gameCanvas"));$("#playBtn").onclick=()=>{show("gameScreen");game.start(false)};$("#continueBtn").onclick=()=>{show("gameScreen");game.start(true)};$("#homeBtn").onclick=()=>{game.stop();show("menu")};$("#parentBtn").onclick=()=>show("parents");$("#settingsBtn").onclick=()=>show("settings");$$(".backBtn").forEach(b=>b.onclick=()=>show("menu"));$("#resetBtn").onclick=()=>{state={coins:0,stars:0,words:0,lastX:90};save();show("parents")};$("#hearWordBtn").onclick=()=>speak(WORDS[state.words%WORDS.length].word);$("#hearSpellBtn").onclick=()=>spell(WORDS[state.words%WORDS.length].word);$("#voiceSelect").onchange=e=>voiceName=e.target.value;$("#voiceRate").oninput=e=>voiceRate=Number(e.target.value);$("#testVoiceBtn").onclick=()=>speak("apple");speechSynthesis.onvoiceschanged=voices;hud();voices();
})();